#Shell variables
# Generated by 'wal'
wallpaper='$HOME/.config/wpg/wallpapers/wallpaper.png'

# Special
background='#120010'
foreground='#e6dafc'
cursor='#e6dafc'

# Colors
color0='#120010'
color1='#DC1C5E'
color2='#EEA21B'
color3='#FFCD01'
color4='#2F638F'
color5='#E34A56'
color6='#A02857'
color7='#aca3bc'
color8='#43013b'
color9='#ff1475'
color10='#ffd711'
color11='#ffff01'
color12='#3081c6'
color13='#ff4c5f'
color14='#dd266e'
color15='#e6dafc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
alpha=ff
