#!/bin/sh 

# Sets a wallpaper, updates the colorscheme and restarts bspwm.
# you can call this script like this:
# wallset <path_to_wallpaper>

[[ $# -ne 1 ]] && echo "Usage: wallset <path_to_wallpaper>" && exit

wallpaper=$1

if ! [[ -f $wallpaper ]] || ! identify $wallpaper > /dev/null 2> /dev/null; 
    then
        echo "$wallpaper is not a valid image"
        exit
fi;
cp $wallpaper ~/.config/rice_assets/Images/wallpaper.png

bspc wm -r
