#!/bin/sh 

[[ $# -ne 1 ]] && echo "Usage: wallset [path_to_wallpaper]" && exit 1

wallpaper=$1

if ! [[ -f $wallpaper ]] || ! identify $wallpaper > /dev/null 2> /dev/null; 
    then
        echo "$wallpaper is not a valid image"
        exit 2
fi;
cp $wallpaper ~/Pictures/Important/wallpaper.png

bspc wm -r
