#!/usr/bin/env bash

killall bspc

# Compositor
picom &

# cursor
xsetroot -cursor_name left_ptr &

# apply colorscheme to spotify
~/.bscripts/wal-spotify.sh > /dev/null&

# Source the colorscheme
echo alpha="ff" >> "${HOME}/.cache/wal/colors.sh"
source "${HOME}/.cache/wal/colors.sh"

# Walllpaper
hsetroot -cover ~/Pictures/Important/wallpaper.png

# Authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1&

# mapcheck
killall osucheck.sh
killall inotifywait
~/.osuthings/osucheck.sh "/home/$USER/.osutmp"&
~/.osuthings/osucheck.sh "/home/$USER/Downloads"&

# Tablet drivers
otd&

# Statusbar
eww -c ~/.config/eww/mybar open bar_right
eww -c ~/.config/eww/mybar open bar_center
eww -c ~/.config/eww/mybar open bar_left
killall polybar
polybar -c ~/.config/eww/mybar/polybar_tray.ini tray&

#Applets
killall blueman-applet
killall pa-applet
killall nm-applet
killall flameshot
blueman-applet&
pa-applet --disable-key-grabbing --disable-notifications& 
nm-applet&
flameshot&
    
# daemons
killall dunst
dunst -lf  $foreground \
      -lb  $color0$alpha \
      -lfr $color9\
      -nf  $foreground \
      -nb  $color0$alpha \
      -nfr $color9 \
      -cf  $foreground \
      -cb  $color0$alpha \
      -cfr $color9 > /dev/null 2>&1 &
thunar --daemon&


# Master layout
for (( i=1; i < 10; i++));do
    #bsp-layout set tiled $i
    true
done

# Sounds
~/.bscripts/sounds.sh&

# idle
killall idle.sh
pgrep idle.sh || ~/.bscripts/idle.sh > /dev/null 2> /dev/null&

# borders
#.bscripts/borders.sh&

# Launch keybinding daemon
killall sxhkd
sxhkd -c ~/.config/bspwm/sxhkdrc > /dev/null 2> /dev/null&
