#!/usr/bin/env bash

sxhkd -c ~/.config/bspwm/sxhkdrc&
# Compositor
killall picom
while pgrep picom > /dev/null; 
do
    # Wait for picom process to end
    # Hacky, but apparently there's not a better way
    # to do this
    sleep 0.1
done;
picom&

# cursor
xsetroot -cursor_name left_ptr &

# Lockscreen
pgrep sxhkd || lock.sh

# Walllpaper
GLWall_dir="${HOME}/Code/GLWall"
#hsetroot -cover ~/.config/rice_assets/Images/lockscreen.png 
pgrep GLWall || $GLWall_dir/GLWall $GLWall_dir/regular_shaders/balatro.glsl&


# Splashscreen
killall unclutter
unclutter --start-hidden &
#pgrep sxhkd || \
    #mplayer ~/Videos/Renders/splash.mp4 
    #mpv --no-input-default-bindings --cursor-autohide=no --osc=no --fullscreen --on-all-workspaces ~/Videos/Renders/splash.mp4

# apply colorscheme to spotify
~/.bscripts/wal_spotify.sh > /dev/null&

# Source the colorscheme
echo alpha="ff" >> "${HOME}/.cache/wal/colors.sh"
source "${HOME}/.cache/wal/colors.sh"

# Cache lockscreen
mantablockscreen -i ~/.config/rice_assets/Images/lockscreen.png&

# Authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1&

# mapcheck
killall osucheck.sh
killall inotifywait
~/.osuthings/osucheck.sh "/home/$USER/.osutmp"&
~/.osuthings/osucheck.sh "/home/$USER/Downloads"&

# Tablet drivers
systemctl --user enable opentabletdriver.service --now

# Statusbar
killall workspaces
killall media_info
killall layout
killall polybar
eww -c ~/.config/eww/mybar kill
eww -c ~/.config/eww/mybar daemon
~/.config/eww/mybar/scripts/ewwcolorscheme
eww -c ~/.config/eww/mybar open bar_right
eww -c ~/.config/eww/mybar open bar_center
eww -c ~/.config/eww/mybar open bar_left
xdotool search --sync --onlyvisible "bar_right" 
polybar -c ~/.config/eww/mybar/polybar_tray.ini tray&

#Applets
killall blueman-applet
killall pa-applet
killall nm-applet
killall flameshot
blueman-applet&
pa-applet --disable-key-grabbing --disable-notifications& 
nm-applet&
flameshot&
    
# daemons
#yawns > /dev/null 2>&1 &
thunar --daemon&


# Master layout
for (( i=1; i < 10; i++));do
    #bsp-layout set tiled $i
    true
done

# Window events
killall winevents.sh
~/.bscripts/winevents.sh&

# idle
pkill -9 idle.sh
~/.bscripts/idle.sh&

yawns&
pacmd load-module module-alsa-source device=hw:Loopback,1,0&

# borders
#.bscripts/borders.sh&

