--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kz87/.config/wpg/wallpapers/wallpaper.png"

-- Special
background="#101012"
foreground="#fffdf8"
cursor="#fffdf8"

-- Colors
color0="#101012"
color1="#CFBFC0"
color2="#64AFA9"
color3="#CFB5AD"
color4="#E6D5CB"
color5="#AD9E98"
color6="#6DC8BF"
color7="#e9e2dd"
color8="#27272c"
color9="#ffdbdf"
color10="#70f5ea"
color11="#ffdec8"
color12="#fff4d5"
color13="#f5c4b0"
color14="#79ffff"
color15="#fffdf8"
